spring :
  datasource :
    url : jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    driverClassName : org.h2.Driver
    username : sa
    password :
  jpa :
    database-platform : org.hibernate.dialect.H2Dialect
    hibernate:
      hbm2ddl:
        auto: create